<?php

namespace SKCMS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \SKCMS\CoreBundle\Repository\SKEntityRepository
{
}
